@baseUrl = http://localhost:3333
@token = {{create_session.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password"
}

###

# @name create_session
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "How to use NestJS with Yup?",
  "content": "I'm trying to validate my request bodies using Zod in a NestJS application. Any tips?"
}

###

# @name edit_question
PUT {{baseUrl}}/questions/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "How to use NestJS with Joi?",
  "content": "I'm trying to validate my request bodies using Joi in a NestJS application. Any tips?"
}

###

# @name delete_question
DELETE {{baseUrl}}/questions/:id
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Authorization: Bearer {{token}}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/how-to-use-nestjs-with-yup
Authorization: Bearer {{token}}